### PR TITLE
bc package required by mqconfig

### PR DESCRIPTION
**Pull request by slattery1**
this adds the bc package to the list of packages to be installed on the image before setting up the queue manager.

### CODE REVIEW

**Comment by arthurbarr** [comment]
I think the change only needs to be made in `efs/install-mq-rhel.sh`, as it's MQ specific.  The reason for installing dependencies in each file, is to keep the dependencies separate.

Also, could you please update the copyright statement to be "2016, 2017"?

**Comment by slattery1** [comment]
Changed copyrights and removed bc from the aws deps.  While I am here, would you want me to update the copyrights in all the files?

**Comment by arthurbarr** [comment]
Thanks for making those changes.  The copyright date only needs to change in files which have been changed this year.  Can you please undo the copyright change to `efs/install-aws-rhel.sh`, which I don't think has changed now?

**Comment by slattery1** [comment]
ok, done.

**Pull request merged**
